name: AcuaticLostWealth
version: 1.3
main: wbe.acuaticLostWealth.AcuaticLostWealth
api-version: 1.21
author: wbe
softdepend: [PlaceholderAPI]
depend: [MythicMobs]
commands:
  AcuaticLostWealth:
    description: AcuaticLostWealth main command
    aliases: [alw]
    permission: acuaticlostwealth.command
